server:
  port: 8585
spring:
  application:
    name: "HOTEL-SERVICE"
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Imt7368@
  jpa: 
    hibernate: 
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Fetching configuration form config server service.
  config:
    import: configserver:http://localhost:8181
  #    spring.config.import.optional.configserver= http://localhost:8181


#configuration to register service with eureka server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka