server:
  port: 8080
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

#        - id: RATING-SERVICE
#          uri: http://localhost:9595
#          predicates:
#            - Path=/ratings/**
#
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZon: http://localhost:8761/eureka

#okta configuration
okta:
  oauth2:
    issuer: https://dev-47824396.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9bkyuvkbEfqb3n5d7
    client-secret: ZWf0UZgvpgLy_uNcYDKMq_I2EJIDOpfbj46h1Zhc
    scopes: openid, email, profile, offline_access, internal